/**: # wildcard for the node name
  ros__parameters:
    gains_xy:
      p: 0.4
      i: 0.01
      d: 0.0
    gains_z:
      p: 0.6
      i: 0.2
      d: 0.005
    epsilon:
      en_route: 0.2
      goal: 0.015
    point:
      object: [0.7, 3.60, -0.825]
      goal: [1.3, 3.60, -0.825]
