/**: # wildcard for the node name
  ros__parameters:
    gains_xy:
      p: 0.6
      i: 0.2
      d: 0.005
    gains_z:
      p: 0.5
      i: 0.3
      d: 0.005
    epsilon:
      en_route: 0.1
      goal: 0.005
