#
# gripper_controllers.yaml
controller_manager:
  ros__parameters:
    update_rate: 250
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    gripper_controller:
      # type: position_controllers/JointGroupPositionController
      type: forward_command_controller/ForwardCommandController


joint_state_broadcaster:
  ros__parameters:
    use_sim_time: true
    joints:
      - left_finger_joint
      # - right_finger_joint

gripper_controller:
    # type: position_controllers/JointGroupPositionController
  # gripper_action_controller:
  ros__parameters:
    joints:
      - left_finger_joint
    interface_name: position
  #     joint_trajectory_controller:
    # type: joint_trajectory_controller/JointTrajectoryController
    # action_monitor_rate: 20.0
    # allow_stalling: false
    # goal_tolerance: 0.01


    # # joint: ''
    # # max_effort: 0.0
    # stall_timeout: 1.0
    # stall_velocity_threshold: 0.001
    # allow_partial_joints_goal: true
    # partial_joint_goal_names: ['left_finger_joint']
      # - right_finger_joint
  # ros__parameters:
  #   type: position_controllers/JointGroupPositionController
  #   joints:
  #     - finger_left_joint
  #     - finger_right_joint
  #   use_sim_time: true

